---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.md
  label: Home
upload_dir: img
public_path: https://github-lfs-nlm.netlify.app/img
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: _site
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
